#30 - User panel
szkola-reacta/team-red-v2-app pull request #31
Opened 2022-09-12 21:32 UTC by bartassmo

2022-09-13 12:32 UTC, olaftarlowski approved these changes
lgtm !

2022-09-14 17:25 UTC, SAK74 requested changes

2022-09-14 17:25 UTC, SAK74 commented on src/components/layout/Navbar.js
> +  const navLinks = [
Greate solution
miałem to zaproponować :)

2022-09-14 17:25 UTC, SAK74 commented on src/components/layout/Navbar.js
> +                    className={({ isActive }) => (isActive ? activeClassName : undefined)}
ale to jest tu zbędne moim zdaniem, NavLink automatycznie dodaje class "active", kiedy jest aktywny

2022-09-14 17:28 UTC, SAK74 requested changes

2022-09-14 17:28 UTC, SAK74 commented on src/components/layout/Navbar.js
> +  ];
Greate solution
miałem to zaproponować :)

2022-09-14 17:33 UTC, SAK74 requested changes

2022-09-14 17:33 UTC, SAK74 commented on src/components/layout/Navbar.js
> +                    className={({ isActive }) => (isActive ? activeClassName : undefined)}
ale to jest tu zbędne moim zdaniem, NavLink automatycznie dodaje class "active", kiedy jest aktywny

2022-09-14 17:34 UTC, SAK74 commented
Generalnie PR trzeba usunąć i puścić od nowa, jak pisałem na slacku, bo ma "chorą" historie...

2022-09-15 09:33 UTC, olaftarlowski commented
zamykam, żeby się znów nie pomieszało, dodaj update do nowego master ;)

2022-09-15 09:33 UTC, closed without merging